-- Create salary_advances table
CREATE TABLE IF NOT EXISTS salary_advances (
    id bigint generated by default as identity primary key,
    employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    amount decimal(15,2) NOT NULL CHECK (amount > 0),
    request_date date NOT NULL DEFAULT CURRENT_DATE,
    reason text,
    status text NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Approved', 'Rejected')),
    approved_by bigint REFERENCES users(id),
    approved_at timestamptz,
    rejection_reason text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE salary_advances ENABLE ROW LEVEL SECURITY;

-- Policies

-- 1. Admins/Managers can view all requests
CREATE POLICY "Admins/Managers view all advances" ON salary_advances
FOR SELECT
USING (
  exists (
    select 1 from employees
    where employees.auth_user_id = auth.uid()
    and employees.role::text IN ('admin', 'manager', 'ADMIN', 'MANAGER')
  )
);

-- 2. Employees can view their own requests
CREATE POLICY "Employees view own advances" ON salary_advances
FOR SELECT
USING (
  auth.uid() IN (
    SELECT auth_user_id FROM employees WHERE id = salary_advances.employee_id
  )
);

-- 3. Employees can create requests (for themselves only)
-- Note: 'employee_id' must match the current user's employee record
CREATE POLICY "Employees create own advances" ON salary_advances
FOR INSERT
WITH CHECK (
  auth.uid() IN (
    SELECT auth_user_id FROM employees WHERE id = salary_advances.employee_id
  )
);

-- 4. Admins/Managers can update status (Approve/Reject)
CREATE POLICY "Admins/Managers update advances" ON salary_advances
FOR UPDATE
USING (
  exists (
    select 1 from employees
    where employees.auth_user_id = auth.uid()
    and employees.role::text IN ('admin', 'manager', 'ADMIN', 'MANAGER')
  )
);
