-- Migration: Tạo bảng lịch sử thay đổi lương
-- Description: Lưu lại lịch sử mọi lần thay đổi lương của nhân viên
-- Created: 2026-01-26

CREATE TABLE IF NOT EXISTS salary_history (
    id bigint generated by default as identity primary key,
    employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    old_salary decimal(15,2),
    new_salary decimal(15,2) NOT NULL,
    change_date date NOT NULL DEFAULT CURRENT_DATE,
    changed_by_employee_id bigint REFERENCES employees(id) ON DELETE SET NULL,
    reason text,
    created_at timestamptz DEFAULT now()
);

-- Index để query nhanh theo employee
CREATE INDEX IF NOT EXISTS idx_salary_history_employee_id ON salary_history(employee_id);

-- Comment
COMMENT ON TABLE salary_history IS 'Lịch sử thay đổi lương của nhân viên';
COMMENT ON COLUMN salary_history.old_salary IS 'Lương cũ trước khi thay đổi';
COMMENT ON COLUMN salary_history.new_salary IS 'Lương mới sau khi thay đổi';
COMMENT ON COLUMN salary_history.changed_by_employee_id IS 'ID nhân viên (Admin/HR) thực hiện thay đổi';
COMMENT ON COLUMN salary_history.reason IS 'Lý do thay đổi (tăng lương, điều chỉnh, v.v.)';

-- Enable RLS
ALTER TABLE salary_history ENABLE ROW LEVEL SECURITY;

-- Policy
CREATE POLICY "Admins can manage salary history" ON salary_history FOR ALL USING (true);
