-- 1. Create rewards_penalties table
CREATE TABLE IF NOT EXISTS rewards_penalties (
    id bigint generated by default as identity primary key,
    employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    type text NOT NULL CHECK (type IN ('Reward', 'Penalty')),
    amount decimal(15,2) NOT NULL,
    reason text,
    date date NOT NULL, -- Date of occurrence, determines payroll month
    status text NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Processed')),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 2. Enable RLS
ALTER TABLE rewards_penalties ENABLE ROW LEVEL SECURITY;

-- 3. RLS Policies for rewards_penalties
-- View: Employees see their own, Admins/Managers see all
DROP POLICY IF EXISTS "View Rewards Penalties" ON rewards_penalties;
CREATE POLICY "View Rewards Penalties" ON rewards_penalties
FOR SELECT
USING (
  (auth.role() = 'authenticated') AND (
    -- Admin/Manager access (Check based on employees.auth_user_id)
    EXISTS (
       SELECT 1 FROM employees 
       WHERE auth_user_id = auth.uid() 
       AND (role::text = 'ADMIN' OR role::text = 'MANAGER' OR role::text = 'HR') -- Cast to text to avoid Enum errors if MANAGER missing
    )
    OR
    -- Employee View Own
    employee_id IN (
       SELECT id FROM employees WHERE auth_user_id = auth.uid()
    )
  )
);

-- Manage: Only Admins/Managers can insert/update/delete
DROP POLICY IF EXISTS "Manage Rewards Penalties" ON rewards_penalties;
CREATE POLICY "Manage Rewards Penalties" ON rewards_penalties
FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM employees 
    WHERE auth_user_id = auth.uid() 
    AND (role::text = 'ADMIN' OR role::text = 'MANAGER' OR role::text = 'HR')
  )
);

-- 4. RLS Policies for Settings & Holidays
-- Settings
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "View Settings" ON settings;
CREATE POLICY "View Settings" ON settings FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Manage Settings" ON settings;
CREATE POLICY "Manage Settings" ON settings USING (
    EXISTS (
        SELECT 1 FROM employees 
        WHERE auth_user_id = auth.uid() 
        AND (role::text = 'ADMIN') -- Only Admin
    )
);

-- Holidays
ALTER TABLE holidays ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "View Holidays" ON holidays;
CREATE POLICY "View Holidays" ON holidays FOR SELECT USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "Manage Holidays" ON holidays;
CREATE POLICY "Manage Holidays" ON holidays USING (
     EXISTS (
        SELECT 1 FROM employees 
        WHERE auth_user_id = auth.uid() 
        AND (role::text = 'ADMIN')
    )
);

-- 5. Seed Data
-- Settings
INSERT INTO settings (key, value) VALUES
('base_salary_min', '5000000'),
('insurance_percent', '10.5'),
('standard_work_days', '22'),
('personal_deduction', '11000000'),
('dependent_deduction', '4400000')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

-- Holidays (2026 Examples)
INSERT INTO holidays (name, date) VALUES
('New Year', '2026-01-01'),
('Lunar New Year (Tet)', '2026-02-17'),
('Independence Day', '2026-09-02')
ON CONFLICT (date) DO NOTHING;
