-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 1. Departments Table
CREATE TABLE departments (
    id bigint generated by default as identity primary key,
    name text NOT NULL,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 2. Users Table (Sync with Supabase Auth in real app, but create table first)
CREATE TABLE users (
    id bigint generated by default as identity primary key,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    role text NOT NULL DEFAULT 'user',
    status text NOT NULL DEFAULT 'active',
    avatar text,
    email_verified_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 3. Employees Table
CREATE TABLE employees (
    id bigint generated by default as identity primary key,
    department_id bigint REFERENCES departments(id) ON DELETE SET NULL,
    user_id bigint REFERENCES users(id) ON DELETE SET NULL,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL UNIQUE,
    phone text,
    hire_date date NOT NULL,
    probation_end_date date,
    salary decimal(15,2),
    annual_leave_quota int DEFAULT 12,
    sick_leave_quota int DEFAULT 5,
    other_leave_quota int DEFAULT 5,
    tax_code text,
    dependents int DEFAULT 0,
    avatar text,
    employment_status text DEFAULT 'Active',
    termination_date date,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 4. Contracts
CREATE TABLE contracts (
    id bigint generated by default as identity primary key,
    employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    contract_type text NOT NULL,
    start_date date NOT NULL,
    end_date date,
    file_path text,
    notes text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 5. Attendances
CREATE TABLE attendances (
    id bigint generated by default as identity primary key,
    employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    date date NOT NULL,
    check_in_time time,
    check_out_time time,
    status text NOT NULL DEFAULT 'pending',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 6. Leave Requests
CREATE TABLE leave_requests (
    id bigint generated by default as identity primary key,
    employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    leave_type text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    reason text,
    status text NOT NULL DEFAULT 'Pending',
    action_by_user_id bigint REFERENCES users(id),
    action_at timestamptz,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 7. Overtime Requests
CREATE TABLE overtime_requests (
    id bigint generated by default as identity primary key,
    employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    date date NOT NULL,
    start_time time NOT NULL,
    end_time time NOT NULL,
    hours decimal(5,2) NOT NULL,
    reason text NOT NULL,
    status text NOT NULL DEFAULT 'Pending',
    approved_by bigint REFERENCES users(id),
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 8. Payslips
CREATE TABLE payslips (
    id bigint generated by default as identity primary key,
    employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    month int NOT NULL,
    year int NOT NULL,
    salary decimal(15,2) NOT NULL,
    ot_hours decimal(5,2) DEFAULT 0,
    ot_salary decimal(15,2) DEFAULT 0,
    bonus decimal(15,2) DEFAULT 0,
    tax decimal(15,2) DEFAULT 0,
    social_insurance decimal(15,2) DEFAULT 0,
    penalties decimal(15,2) DEFAULT 0,
    advance_amount decimal(15,2) DEFAULT 0,
    net_pay decimal(15,2) NOT NULL,
    status text NOT NULL DEFAULT 'Generated',
    notes text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 9. Assets
CREATE TABLE assets (
    id bigint generated by default as identity primary key,
    name text NOT NULL,
    asset_tag text NOT NULL UNIQUE,
    purchase_date date NOT NULL,
    purchase_cost decimal(15,2) NOT NULL,
    status text NOT NULL DEFAULT 'Available',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 10. Asset Assignments
CREATE TABLE asset_assignments (
    id bigint generated by default as identity primary key,
    asset_id bigint NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
    employee_id bigint NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    assigned_date date NOT NULL,
    returned_date date,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 11. Job Openings (Recruitment)
CREATE TABLE job_openings (
    id bigint generated by default as identity primary key,
    department_id bigint REFERENCES departments(id) ON DELETE SET NULL,
    title text NOT NULL,
    description text,
    status text NOT NULL DEFAULT 'Open',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 12. Candidates
CREATE TABLE candidates (
    id bigint generated by default as identity primary key,
    job_opening_id bigint NOT NULL REFERENCES job_openings(id) ON DELETE CASCADE,
    first_name text NOT NULL,
    last_name text NOT NULL,
    email text NOT NULL,
    phone text,
    cv_path text,
    status text NOT NULL DEFAULT 'Pending',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 13. Settings (Global config)
CREATE TABLE settings (
    id bigint generated by default as identity primary key,
    key text NOT NULL UNIQUE,
    value text,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- 14. Holidays
CREATE TABLE holidays (
    id bigint generated by default as identity primary key,
    name text NOT NULL,
    date date NOT NULL UNIQUE,
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Enable Row Level Security (RLS) - Important for Supabase
ALTER TABLE departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE employees ENABLE ROW LEVEL SECURITY;
ALTER TABLE contracts ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendances ENABLE ROW LEVEL SECURITY;
ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE overtime_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE payslips ENABLE ROW LEVEL SECURITY;
ALTER TABLE assets ENABLE ROW LEVEL SECURITY;
ALTER TABLE asset_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_openings ENABLE ROW LEVEL SECURITY;
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE holidays ENABLE ROW LEVEL SECURITY;

-- Creating basic policies (Open for now to allow seeding, you should restrict this later)
CREATE POLICY "Public Read Access" ON departments FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON employees FOR SELECT USING (true);
CREATE POLICY "Public Read Access" ON job_openings FOR SELECT USING (true);
